---
- name: lets try include
  hosts: all
  gather_facts: flase

  tasks: 
    - debug: 
        msg: this msg included in play1.yaml
         
            
    - include: play2-task2.yaml

- include: entire-playbook.yaml
 


...
 
