---
- name: this lab for loops
  hosts: ubuntu
  
  
  tasks: 
    - name: test with_nested which loops a loop into another one
      file: 
        dest: "/home/{{ item.0 }}/{{ item.1 }}"
        owner: "{{ item.0 }}"
        group: "{{ item.0 }}"
        state: directory
        with_nested:
          - [abood, ali, yaser, obaida]
          - [ photo, movies, documents]
        
      
