---
- hosts: localhost
  connection: local 
  
  
  
  tasks:
    - name: creat a security group
      ec2_group:
        name: abood
        description: Ansible security Group
        region: us-east-2
        rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
      
      
    - name: launch EC2-instances
      ec2:
        key_name: ansible-try 
        instance_type: t2.micro
        image: ami-05220ffa0e7fce3d1
        wait: yes
        group: abood
        count: 2
        region: us-east-2
        instance_tags:
          Name: Ansible
        state: running
      register: ec2 
        
           
    - name: add hosts
      add_host: 
        hostname: "{{item.public_ip}}"
        groups: ansiblehosts
      with_items: "{{ec2.instances}}"
    
     
    - name: print froups.ansiblehosts
      debug: 
        var: groups.ansiblehosts 



















 
# Three dote indecte the end of the A YAML decument.
...
          
