---
- name: Test ssh connection
  hosts: linux
  gather_facts: false
  vars:
    name_list:
      - item1
      - item2
      - item3
      - item4
  tasks:
    - name: show me the entire list
      debug:
        msg: "{{name_list}}"
      
    - name: show me the first itme in the list Dict. way
      debug:
        msg: "{{name_list.0}}"
    - name: show me the the third item  in python way
      debug:
        msg: "{{name_list[2]}}"




          
  
